import { Inter } from 'next/font/google'
import './globals.css'
import montserrat from '@/assets/fonts/montserrat'
import montserrat_Alternates from '@/assets/fonts/montserrat_Alternates'
import roboto from '@/assets/fonts/Roboto'

export const metadata = {
     title: 'Create Next App',
     description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
     return (
          <html
               lang='en'
               className={`${montserrat.variable} ${montserrat_Alternates.variable} ${roboto.variable}`}
          >
               <body>{children}</body>
          </html>
     )
}
